initial commit
binary-com/chrome-extension pull request #1
Opened 2016-11-18 07:43 UTC by AlexShpak

2016-11-18 07:47 UTC, ashkanx requested changes

2016-11-18 07:47 UTC, ashkanx commented on popup.html
> +            <img class="logo-symbol" src="logo/binary-symbol-logo.svg">
You can get the logo directly from binary-style

2016-11-18 07:47 UTC, ashkanx commented on popup.html
> +            <img class="logo-text" src="logo/binary-type-logo.svg">
same as above

2016-11-18 10:24 UTC, mohammad-deriv approved these changes

2016-11-22 03:59 UTC, ashkanx commented
@AlexShpak Please add the Favicon directly from binary-style
https://style.binary.com/#logo-section

2016-11-28 01:12 UTC, ashkanx approved these changes

2016-11-28 01:12 UTC, merged